import {
  signUpQuery,
  checkEmailQuery,
  addProjectQuery,
  addUserProjectsQuery,
  getProjectsQuery,
  deleteProjectQuery,
  editProjectQuery,
  getTasksQuery,
  getTasksSectionQuery,
  deleteTaskQuery,
  getSpecificProjectQuery,
  getMembersQuery,
  addSectionQuery,
  deleteSectionQuery,
  editSectionQuery,
  editTaskQuery,
} from './quieres';

import { connection, buildDb } from './config';

export {
  checkEmailQuery,
  addProjectQuery,
  addUserProjectsQuery,
  getSpecificProjectQuery,
  deleteProjectQuery,
  getMembersQuery,
  getProjectsQuery,
  editProjectQuery,
  getTasksQuery,
  getTasksSectionQuery,
  deleteTaskQuery,
  signUpQuery,
  editTaskQuery,
  connection,
  buildDb,
  addSectionQuery,
  deleteSectionQuery,
  editSectionQuery,
};
